version: '3.4'

services:
  api:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: github.com/juniorrosul/pismo-api
    container_name: juniorrosul-pismo-api
    ports:
      - "8080"
    networks:
      - local
    depends_on:
      - "mysql"

  mysql:
    image: mysql
    container_name: mysql
    ports: 
      - 3306:3306
    environment:       
      - MYSQL_USER=madsonjr
      - MYSQL_PASSWORD=pismo
      - MYSQL_DATABASE=pismo
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - local

networks:
  local:
    driver: bridge